LuaCEmbedResponse * LuaCEmbed_send_multi_return(LuaCEmbedTable *table);
LuaCEmbedResponse * LuaCEmbed_send_str(const char *text);
LuaCEmbedResponse * LuaCEmbed_send_raw_string(const char *text, lua_Integer size);
LuaCEmbedResponse * LuaCEmbed_send_str_reference(const char *text);
LuaCEmbedResponse * LuaCEmbed_send_raw_string_reference(const char *text, lua_Integer size);
LuaCEmbedResponse * LuaCEmbed_send_table(LuaCEmbedTable *table);
LuaCEmbedResponse * LuaCEmbed_send_evaluation(const char *function);
LuaCEmbedResponse * LuaCEmbed_send_double(double value);
LuaCEmbedResponse * LuaCEmbed_send_bool(bool value);
LuaCEmbedResponse * LuaCEmbed_send_long(lua_Integer value);
LuaCEmbedResponse * LuaCEmbed_send_error(const char *format, ...);